### 1、Import tensorflow and use tensorflow to define a constant.

In [1]:
import tensorflow.compat.v1 as tf
with tf.Session() as sess:
    x = tf.constant(35.0)
    print(sess.run(x))

35.0


### 2、Use tensorflow to print 'Welcome to Huawei'.

In [2]:
with tf.Session() as sess:
    a=tf.constant('Welcome to Huawei', name='a')
    print(sess.run(a))

b'Welcome to Huawei'


### 3、Use tensorflow to define two numeric constants,then calculate them and print the result.

In [3]:
with tf.Session() as sess:
    a=tf.constant(2.0)
    b=tf.constant(3.0)
    c=a+b
    print(sess.run(c))

5.0


### 4、Randomly generate two matrices using tensorflow, calculate and print the result of their multiplication.

In [4]:
with tf.Session() as sess:
    var1 = tf.compat.v1.get_variable("var1", initializer=tf.compat.v1.random_uniform([3, 3], minval=1, maxval=10, dtype=tf.int32))
    var2 = tf.compat.v1.get_variable("var2", initializer=tf.compat.v1.random_uniform([3, 3], minval=1, maxval=10, dtype=tf.int32))
    sess.run(tf.global_variables_initializer())
    mat = tf.matmul(var1, var2)
    print(sess.run(mat))

[[ 23  31  58]
 [ 47  44  60]
 [ 67  75 123]]


### 5、Try to use your own handwriting number to do image recognition

In [5]:
import tensorflow as tf

    # Загружаем датасет MNIST
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)), # Входной слой: 784 нейрона (28х28) статический
    tf.keras.layers.Dense(502, activation='relu'), # Первый скрытый слой 502 нейрона
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(256, activation='relu'), # Второй скрытый слой 256 нейронов
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10) # Выходной слой 10 нейронов (статический)
])
predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy']) # Компиляция модели
model.fit(x_train, y_train, epochs=15) # Тренировка модели 15 эпох
print("Модель успешно обучена")
model.save('mnist.h5') # Сохранение модели в файл чтобы заново не переучивать
print("Модель сохранена как mnist.h5")

model.evaluate(x_test, y_test, verbose=2)

Epoch 1/15
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2223 - accuracy: 0.9316
Epoch 2/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1073 - accuracy: 0.9670
Epoch 3/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0818 - accuracy: 0.9744
Epoch 4/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0659 - accuracy: 0.9790
Epoch 5/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0575 - accuracy: 0.9818
Epoch 6/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0472 - accuracy: 0.9852
Epoch 7/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0462 - accuracy: 0.9854
Epoch 8/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0426 - accuracy: 0.9870
Epoch 9/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0388 - accuracy: 0.9872
Epoch 10/15
1875/1875 [==============================] - 5s 3ms/step - loss: 0.036

[0.0935116782784462, 0.9804999828338623]

In [6]:
from PIL import ImageFile, Image, ImageOps, ImageEnhance
from keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy

#ImageFile.LOAD_TRUNCATED_IMAGES = True
!wget -nc https://raw.githubusercontent.com/MorozoffM4x/HCIA-AI/main/2.jpg
img = Image.open("2.jpg") # Можно подгрузить изображения *.jpg где * - цифра
    # загружаем сохранённую модель
model = load_model('mnist.h5')
img = img.resize((28,28))
    # конвертируем rgb в grayscale
img = img.convert('L')
    # Инвертируем изображение
img = ImageOps.invert(img)
    # Увеличиваем контраст в 10 раз
enhancer = ImageEnhance.Contrast(img)
img = enhancer.enhance(10)

#img.show() # Тестовая проверка полученного изображения
img= image.img_to_array(img)
#img = numpy.array(img)
    # изменение размерности для поддержки модели ввода и нормализации
img = img.reshape(1,28,28,1)
img = img / 255.0
    # предсказание цифры
res = model.predict([img])[0]

print("Цифра:", numpy.argmax(res), "Точность:", max(res))


Файл ‘2.jpg’ уже существует — не загружается.

Цифра: 2 Точность: 39.75063


Очень низкая точность из-за плохой подготовкии изображений.