# 1.Print 'Hello HCIA'.

In [1]:
print("Hello HCIA")

Hello HCIA


# 2.Define two variables and calculate their sum.

In [2]:
a=3
b=4
a+b

7

# 3.Define a list and replicate in three different ways.

In [3]:
a=3
b=[1,2,3,4,5]
sorted(b * a)


[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5]

# 4.Define two lists and merge them together.

In [4]:
from itertools import chain
a=[6,7,8,9]
b=[1,2,3,4,5]
c=list(chain(b,a))
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# 5. Get the last element of the list and print it.

In [5]:
a=[6,7,8,9]
print(a[-1:])

[9]


# 6.Define a tuple that contains only one element.

In [6]:
t=("aa")

# 7.Define a three-line long string.

In [7]:
s = """ this is a very
        long string if I had the
        energy to type more and more ..."""

# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [8]:
t=("one", "two", "three")
for x in t:
    print(x)

one
two
three


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [9]:
def mul(m, n)->int:
    return m*n

mul(8,6)

48

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [10]:
import numpy as np
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [11]:
import numpy as np
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [12]:
import numpy as np
print(np.arange(15))
print(np.arange(3, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 4]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [13]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a*b

array([[ 5, 12],
       [21, 32]])